### ISSUE TITLE
AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.

### ISSUE THREAD

**Issue by turbocarte-foodradar** [Azure-Samples/active-directory-b2c-msal-node-sign-in-sign-out-webapp#1]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Basically, I use the exact same code (with exceptions of the client secret and the application id).
The confidentialClientConfig is the same (again, with my own clientId, authority, etc...)
The getAuthCode function and the endpoints ("/signin", "/redirect", ...) are the same.
The AD B2C configuration is exactly as prescribed.

### Any log messages given by the failure
>{"errorCode":"invalid_request","errorMessage":"undefined - [undefined]: AADB2C90079: Clients must send a client_secret when redeeming a confidential grant.\r\nCorrelation ID: bfac0c4b-d0c4-423b-9889-7c846145813d\r\nTimestamp: 2022-03-24 16:16:52Z\r\n - Correlation ID: undefined - Trace ID: undefined","subError":"","name":"ServerError"}

Debug console:
[Thu, 24 Mar 2022 16:24:55 GMT] : [00ee5b5f-c32a-458c-9ee3-816c128a767c] : @azure/msal-node@1.7.0 : Verbose - createAuthority called
[Thu, 24 Mar 2022 16:24:55 GMT] : [00ee5b5f-c32a-458c-9ee3-816c128a767c] : @azure/msal-node@1.7.0 : Verbose - Auth code client created
[Thu, 24 Mar 2022 16:24:55 GMT] : [00ee5b5f-c32a-458c-9ee3-816c128a767c] : @azure/msal-common@6.1.0 : Info - in acquireToken call

### Expected/desired behavior
>I would expect the acquireTokenByCode function to return the access token succesfully.

### OS and Version?
> Windows 10.

### Versions
>@azure/msal-node@1.7.0

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by turbocarte-foodradar** [comment]
Just in case it has any value at all, I use Webpack.

**Comment by kengaderdus** [comment]
@turbocarte-foodradar 

Thank you for your feedback. 

Make sure you're using the app secret for the app that you registered. Also ensure the authorities, say for sign in sign up have the correct user-flow in the URL  

The app must be a web app (confidential), not a single-page app (SPA). 

The web app represented [here](https://github.com/Azure-Samples/active-directory-b2c-msal-node-sign-in-sign-out-webapp) does not return an access token, only ID token to identify a user, so we're using it to sign in and sign out a user, edit profile and reset password. You won't retrieve an access token from `acquireTokenByCode` function if no scopes are passed. 

If you want to learn how to retrieve an access token, [use this repo](https://github.com/Azure-Samples/active-directory-b2c-msal-node-sign-in-sign-out-webapp/tree/main/call-protected-api), it's simply a folder (`call-protected-api)`) in the repo you used. 

Also, make use of the [resources](https://github.com/Azure-Samples/active-directory-b2c-msal-node-sign-in-sign-out-webapp/blob/main/call-protected-api/README.md#resources).

Please let us know if this is helpful. 

Thanks.

**Comment by turbocarte-foodradar** [comment]
Thank you @kengaderdus. The user-flow uri are working nicely. My app is confidential (Express/NodeJS web site running on Nginx, on an Azure VM). 
I'll keep searching and I'll post some more details tomorrow if I still have problems.

**Comment by turbocarte-foodradar** [comment]
The "/signin" part works fine:
getAuthCode(b2cPolicies.authorities.signUpSignIn.authority, [], APP_STATES.login, res);

The "/redirect" is called and then, the call to pca.acquireTokenByCode(tokenRequest) fails;

The tokenRequest contains the following (I erased some parts of the code value):

_**tokenRequest**
{redirectUri: '[http://localhost:3000/redirect]()', authority: '[https://FoodRadarADB2C.b2clogin.com/FoodRad…nmicrosoft.com/B2C_1_FoodRadar_SignupSignIn]()', code: 'eyJra...xNSIsInZlciI6Ij…gSr4aHIaPQcaY_YjgdYfCs.NenbQRQ7se_fKBi1t2Y7Cg'}
authority:'[https://FoodRadarADB2C.b2clogin.com/FoodRadarADB2C.onmicrosoft.com/B2C_1_FoodRadar_SignupSignIn]()'
code:'eyJra...xNSIsInZlciI6Ij…gSr4aHIaPQcaY_YjgdYfCs.NenbQRQ7se_fKBi1t2Y7Cg'
redirectUri:'[http://localhost:3000/redirect]()'_

I also tried adding the client secret as a property of tokenRequest, but it doesn't work either.

**Comment by turbocarte-foodradar** [comment]
Also, **confidentialClientConfig** does contain the client secret.

**Comment by turbocarte-foodradar** [comment]
Also, I have the same error when I run the user flow from the Azure AD B2C test page.

**Comment by turbocarte-foodradar** [comment]
When I use the sample code with my AD B2C account infos, it works. So it has something to do with my own code. **_You can close this issue and mark it as resolved_** ;-)
Thank you very much

**Comment by turbocarte-foodradar** [comment]
I was calling PublicClientApplication instead of ConfidentialClientApplication. **Totally my fault**. Thank you.

**Comment by kengaderdus** [comment]
@turbocarte-foodradar 

Thanks you for your feedback.
