### ISSUE TITLE
Getting a code challenge error when signin-in

### ISSUE THREAD

**Issue by joelbloch** [Azure-Samples/active-directory-b2c-msal-node-sign-in-sign-out-webapp#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I follow the exact documentation provided at the url https://docs.microsoft.com/azure/active-directory-b2c/configure-a-sample-node-web-app, and pressing the sign-in button ends up in error

### Any log messages given by the failure
> AADB2C99059: The supplied request must present a code_challenge

### Expected/desired behavior
> Sign-in sucessfully, I don't know how to add a code challenge on this demo app, or clear instructions how to do so.

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by kengaderdus** [comment]
@joelbloch 

Thank you for your feedback. The sample uses Microsoft Authentication Library (MSAL), so you do not generate the code challenge yourself. We'll investigate and get back when we've something. Meanwhile, in the `package.json` file, make sure you're using **msal version 1.11.0** by updating it.

**Comment by kengaderdus** [comment]
@joelbloch 

We've tested the sample and procedures, and everything works as expected from our end. You could give us more information to help us reproduce the error. Make sure all the values in the `.env` files are from your own environment and are accurate. Also, while registering your application in Azure portal, make sure that you select 'web' as the target platform.

<img width="620" alt="Screenshot 2022-07-14 130822" src="https://user-images.githubusercontent.com/88311008/178958910-3413863b-50a4-4978-a46e-18c894d31d1e.png">
