### ISSUE TITLE
Seeking clarification of which approach, documentation and repositories to use for a Node.js web app

### ISSUE THREAD

**Issue by oshihirii** [Azure-Samples/active-directory-b2c-msal-node-sign-in-sign-out-webapp#4]
### This issue is for a:
```
- [ X ] documentation issue or request
```

I am trying to learn how to implement Azure B2C authentication in a Node.js web app.  

This includes the following actions:

 - Sign In / Sign Out / Edit Profile  
 - Authenticating calls made to the app's own api (i.e when calling Express routes within the Node application)  

I am confused when I look at the `Web Apps and APIs` section in the [Azure Active Directory B2C code samples](https://learn.microsoft.com/en-us/azure/active-directory-b2c/integrate-with-app-code-samples) documentation:

https://learn.microsoft.com/en-us/azure/active-directory-b2c/integrate-with-app-code-samples#web-apps-and-apis  

It lists two GitHub repositories for Node.js:  

https://github.com/Azure-Samples/active-directory-b2c-msal-node-sign-in-sign-out-webapp

https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi

**Question 01:**   
What is the difference between these two repo's - when should I use one over the other?  

_Screenshot of relevant section:_  
![node_web_apps_and_apis](https://user-images.githubusercontent.com/5090307/204988347-9c3f144b-3644-4231-9780-3fe1987ce851.png)

**Question 02:**  
I am also finding it difficult to differentiate between the different resources mentioned in the README of this repo.  

The links are so similarly named - can anyone please clarify the difference between these resources?  

`Configure authentication in a sample Node.js web application by using Azure AD B2C`    
https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-a-sample-node-web-app
  
  
`Enable authentication in your own Node web application using Azure AD B2C`    
https://learn.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-in-node-web-app
  
  
`Configure authentication in a sample Node.js web API by using Azure AD B2C`   
https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-in-sample-node-web-app-with-api
  
  
`Enable authentication in your own Node.js web API by using Azure AD B2C`    
https://learn.microsoft.com/en-us/azure/active-directory-b2c/enable-authentication-in-node-web-app-with-api

_Screenshot of README:_  
![repo_readme](https://user-images.githubusercontent.com/5090307/204989010-1b549cdc-4558-4f8c-915f-848452713891.png)

**Comment by oshihirii** [comment]
I am just realizing that this article:

Configure authentication in a sample Node.js web API by using Azure Active Directory B2C  
https://learn.microsoft.com/en-us/azure/active-directory-b2c/configure-authentication-in-sample-node-web-app-with-api

seems to implement BOTH repos:

 - https://github.com/Azure-Samples/active-directory-b2c-msal-node-sign-in-sign-out-webapp   
 - https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi  

and covers BOTH scenarios:

 - Sign In, Sign Out, Edit Profile via Azure AD B2C (using these node packages:  `express-session` and `@azure/msal-node`)
 - Calling your web app's API authenticated by Azure AD B2C (using these node packages:  `passport` and `passport-azure-ad`)

But it requires:

 - 2 x app registrations in Azure 
 - 2 x node applications  

I am very confused why you need to create 2 app registrations and 2 node applications.

In regards to the 2 x node applications:

 - My web app (Express, Node application) _IS_ my web api     
 
 - Why do I need to create two applications - a node web app AND another node app for the api?    

And why do I have to use the concept of scopes?  

I have not done this before (apart from in the context of creating Microsoft Graph applications) and don't know how to do it.

**Comment by oshihirii** [comment]
(In case it helps others, I still have the above questions but am finding this Microsoft YouTube playlist very helpful to understand some of the surrounding topics:  https://youtube.com/playlist?list=PL3ZTgFEc7LyvP6Jo4kfgEjzgi7UdnzR-t)

**Comment by oshihirii** [comment]
(And this is a helpful article series:  https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-overview)

**Comment by oshihirii** [comment]
In case it helps others, I still have the above questions but am finding this Microsoft YouTube playlist very helpful to understand some of the surrounding topics: 

Identity for Developers Playlist by Microsoft Security  
https://youtube.com/playlist?list=PL3ZTgFEc7LyvP6Jo4kfgEjzgi7UdnzR-t

And this is a helpful article series:   

What is the Microsoft identity platform?  
https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-overview

**Comment by oshihirii** [comment]
I have come across this issue comment:

https://github.com/Azure-Samples/active-directory-b2c-msal-node-sign-in-sign-out-webapp/issues/1#issuecomment-1078800453

Which seems to provide instruction on how to authorise an API call on your own app:  

> If you want to learn how to retrieve an access token, [use this repo](https://github.com/Azure-Samples/active-directory-b2c-msal-node-sign-in-sign-out-webapp/tree/main/call-protected-api), it's simply a folder (`call-protected-api`) in the repo you used.

But that folder utilises yet another paradigm using this combination of Node packages:

`express-session` and `@azure/msal-node` and `axios` (to make http calls to your own app API).  

So perhaps that removes the need to create 2 x Node applications.  

But it doesn't provide instructions on how to setup:

 - Application Registrations (do I still need 2 application registrations)  
 - Scopes

**Comment by kengaderdus** [comment]
@oshihirii 

Thank you for you feedback. 

We didn't want to duplicate content in the repo and in our docs site (learn.microsoft.com), so we put the article in the repo as a resource. 


**Difference between the two articles** 

- Configure authentication in a sample... - here we provide a sample that you can use with your own Azure AD B2C tenant settings
- Enable authentication in your own... - here, we teach you how the sample app itself was built. So, you build it, and then add authentication. 

These scenarios apply to both the adding authentication in a web app as well as calling your own API.

**App registration**

- For the adding authentication, you only register 1 app in the portal
- For adding authentication and then call an API, you register 2 apps in the portal. First app is one that signs in the user, acquires an access token to call an API, the second app is the API itself.  


I advise you that you use the resource articles and follow all the instructions. For example, in the _Enable authentication in your own..._ article, one of the pre-requisites is you complete the steps in _Configure authentication in a sample..._ article. That's where you learn how to register apps and configure scopes (in the case of calling an API)


I hope this explanation helps. 

Thank you.

**Comment by oshihirii** [comment]
Thanks for the information.  

After posting my question, I dug in deeper to the repos and documentation.  

I added my understandings as a pull request in the hopes they can clarify things for others who are new to these resources:

https://github.com/Azure-Samples/active-directory-b2c-msal-node-sign-in-sign-out-webapp/blob/966d66291ad5067df8ecb3b8913d1207b929028e/README.md

Thank you.

**Comment by kengaderdus** [comment]
@oshihirii 

We'll review the PR. We'll proceed to close this issue.
