### ISSUE TITLE
After clicking on 'revoke sessions' in Azure B2C user profile, the user still appears logged in in Node app

### ISSUE THREAD

**Issue by oshihirii** [Azure-Samples/active-directory-b2c-msal-node-sign-in-sign-out-webapp#6]
### This issue is for a:
```
- [  X ] documentation issue or request
```

I am just learning how to do B2C authentication.  

Because I have to frequently test the sign in process, I need to somehow 'sign out', so that I can 'sign in' again.    

I thought that I could do this by clicking on 'revoke sessions' in `Azure AD B2C` > `Users` > `User` profile .  

But after I do this, restart the Node app, and click on the 'Sign In' link again, 'nothing happens' - or rather the Node app returns the AuthToken value as if the user is already signed in.  

### Minimal steps to reproduce

 - Call the `signin` route and sign in  
 - The user will see the redirect page (this is the desired behaviour)  
 - Go to `Azure AD B2C` > `Users` > `User` profile and click on 'revoke sessions' button  
 - Stop local Node application
 - Start local Node application
 - Call the `signin` route again  
 - Nothing happens on the frontend, but in the backend Node logs the `AuthToken` value as if the user is already signed in  

### Any log messages given by the failure
There are no error messages, but calling the `signin` route the second time returns the `AuthToken` value (which it shouldn't cause the user should have been signed out).  

### Expected/desired behavior
When calling the `signin` route the second time, I am expecting to see the login form again, so the user can sign in again.  

### Versions
```
"@azure/msal-node": "^1.14.4",
"express-session": "^1.17.3",
```

(Edit:  I _am_ able to call the 'signout' route to sign the user out, but would still be interested to know why `revoke sessions` doesn't force sign the user out)

**Comment by kengaderdus** [comment]
@oshihirii 

Thank you for your feedback! The code sample provides a way to sign out a user. Currently, Azure AD B2C doesn't support user session revocation from the Azure portal. However, you can achieve this task by using [Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/azure/active-directory-b2c/manage-users-portal#revoke-a-consumer-users-session) or [Microsoft Graph API](https://learn.microsoft.com/en-us/graph/api/user-revokesigninsessions). #please-close

**Comment by kengaderdus** [comment]
@oshihirii 

Thank you for your feedback! The code sample provides a way to sign out a user. Currently, Azure AD B2C doesn't support user session revocation from the Azure portal. However, you can achieve this task by using [Microsoft Graph PowerShell](https://learn.microsoft.com/en-us/azure/active-directory-b2c/manage-users-portal#revoke-a-consumer-users-session) or [Microsoft Graph API](https://learn.microsoft.com/en-us/graph/api/user-revokesigninsessions).
